### ISSUE TITLE
Add Reference Posts from UDOT

### ISSUE THREAD

**Issue by gregbunce** [agrc/porter#172]
# Summary

- **Proposed Readable Name**: Utah Mile Reference Posts
- **Proposed Internal Dataset Name**: UDOT_MileReferencePosts
- **Proposed External Dataset Name**: Utah_Mile_Reference_Posts
- **Proposed Data Category**: Transportation
- **Data Description**: Reference Post locations along Utah highways.
Reference Posts are signs located in physical locations. They stay in roughly the same place over time and do not change when other sections of the road are realigned. This layer also contains current ALRS linear measures (LM) for the sign feature.
- **Source Agency/Entity**: UDOT
- **Contact**: Kelli Bacon
- **Update Frequency**: Quarterly

This dataset is the latest and greatest from UDOT for Utah mile posts.  UDOT maintains this layer in their ArcGIS Portal and has shared the URL with us and has shared it via our [open data site](https://opendata.gis.utah.gov/datasets/uplan::rp-stationing).

Because of UDOT's funky naming on this layer, UGRC has created a new Item in our AGOL with the name [Utah UDOT Mile Reference Posts](https://opendata.gis.utah.gov/datasets/utah::utah-udot-mile-reference-posts/explore) and pointed the feature service to UDOT's Portal item.  This allows us to name the layer as needed, with UDOT continuing to update the data.  The only caveat is that the metadata will not remain in scyn with UDOT's Portal layer.  This is not a problem in this case, as UDOT has UGRC create the metadata for this layer.

This layer will replace both the existing mile post and 10th of mile post data we are hosting in SGID (which are based on the LRS measures).  This new layer is based on the physical signs in the ground.   We will provide a link in the data page to the LRS-based data in case folks are looking for it, but UDOT is recommending that folks use the mile reference post data when possible (the physical signs on the ground).

## The data should be available in

1 _Check [x] all the areas where you expect the data to show up._

- [x] Internal SGID
- [x] Open SGID
- [x] ArcGIS Online
- [x] Open Data

## The data is of high quality

~- [ ] Sweeper checks have run and passed (name on `2021/00/00`)~
- [x] The minimum requirements for [metadata](https://gis.utah.gov/about/policy/sgid/) are populated (@gregbunce on `2022/03/22`)
- [x] The data complies with our [domain rules](https://gis.utah.gov/about/policy/sgid/) (@gregbunce on `2022/02/02`)

## Where is the data source

_Choose one._

~- [ ] Internal SGID~
- [x] Farm from AGOL ([udot portal iteml](https://data-uplan.opendata.arcgis.com/datasets/uplan::rp-stationing))

## Action items

1. _Assign a person who should complete the task by replacing `name` with their github `@name`._
1. _Check [x] the box when the task is completed and add the date of completion._
1. _~Strike~ out all items that do not apply._

- [x] Add data to the Internal SGID (@gregbunce, completed: `2022/02/02`)
- [x] Configure forklift for Farm from AGOL (@stdavis, completed: `2022/03/21`)
- [x] Update relevant [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, completed: `2022/03/28`)
- [x] Add a [Stewardship](https://docs.google.com/spreadsheets/d/11ASS7LnxgpnD0jN4utzklREgMf1pcvYjcXcIcESHweQ/edit#gid=1) record (@gregbunce, completed: `2022/03/22`)
- [x] Complete a `SGID.META.AGOLItems` record (@gregbunce, completed: `2022/02/02`)
~- [ ] Complete an [AGOLItems_shelved](http://utah.maps.arcgis.com/home/item.html?id=1760fbedbc7e49429aa6c0c3ab1442ec) record for any `static` or `shelved` item (name, completed: `2021/00/00`)~

## :robot: Automation validation

1. _Assign yourself or someone to check the item by replacing `name` with their github `@name`._
1. _Check [x] the box and add the date of verification `2020/01/01` when the task is verified._
1. _~Strike~ out all items that do not apply._

- [x] Open SGID via cloudb (@steveoh on `2022/03/29`)
- [x] ArcGIS Online via forklift (@stdavis on `2022/03/28`)
- [x] [Auditor](https://github.com/agrc/Auditor) ran successfully (@jacobdadams on `2022/03/29`)
- [x] [Open Data](https://opendata.gis.utah.gov) (@gregbunce, on `2022/03/29`)
- [x] [gis.utah.gov](https://gis.utah.gov/data) data pages (@gregbunce, on `2022/03/29`)
- [x] [sgid-index](https://gis.utah.gov/data/sgid-index) (@steveoh on `2022/03/29`)

## Notification

- [x] Twitter (@steveoh)

## Group Task Assignments

1. _Check [x] the box when you have assigned all the tasks relevant to your group._

- [x] Data Team (@gregbunce)
- [x] Dev Team (@steveoh)
- [x] Cadastre Team (@rkelson)

**Comment by gregbunce** [comment]
@stdavis this one's a little funky so let me know if you want to chat about any of it.  for one, they host the data in the ESRI Portal (not AGOL), so, the URL might look different.  Also, they are not able to rename the layer name but i was hoping we could so something fancy and use the name we give it in Internal as the name we expose in Open SGID and Open Data.  is that possible?  (seems like we can do that for Open SGID, but maybe not for Open Data).

**Comment by jacobdadams** [comment]
I'm not Scott, but I'm pretty sure for Open Data we're stuck with whatever name they've given it in their Portal, because it's just a direct reference to that item. My vote would be for keeping the name consistent across SGID products, but that's just me.

**Comment by gregbunce** [comment]
just dropping this here for everyone's reference.  The data we're introducing is Mile Reference Posts (they no longer maintain Mile Points but it can be derived from the data we're introducing using the 'Measure' field.  The 'Legend' field contains the Reference Post)
![image](https://user-images.githubusercontent.com/16906316/151630844-b5d9a3f7-5721-4c63-8131-a727d89d5f17.png)

**Comment by stdavis** [comment]
I don't believe that it matters what the source layer name is when we are pulling from AGOL into internal. We can rename it to whatever we want. I checked out the source and we should be able to access it fine.

**Comment by stdavis** [comment]
@gregbunce Forklift will not create new feature classes in internal, it will only update existing ones. I un-strikethrough-ed the task to create this. I wasn't sure who to assign it to.

**Comment by gregbunce** [comment]
Thanks for the clarification, Scott. I understand.  I'll get it loaded.
Once it exists, forklift will keep it updated, correct?

**Comment by stdavis** [comment]
> Thanks for the clarification, Scott. I understand. I'll get it loaded. Once it exists, forklift will keep it updated, correct?

Yes, once that forklift PR is merged.

**Comment by steveoh** [comment]
I'd like to see what comes of the meeting with UDOT to see what the real story is and what work is required here.

**Comment by gregbunce** [comment]
@stdavis i added the layer to Internal and created a row in the meta table.
i feel like we can move forward with this piece while we work out the udot name, right? 

note: let me know if you have issues setting up farm to agol. i had to download the feature service as a shapefile so the fields got a little funky. I did my best to match what's in the feature service but i might have missed something.  just let me know and i can fix it at the feature class level (in Internal). 

![image](https://user-images.githubusercontent.com/16906316/152215894-1eba1828-d0ee-416d-acc1-e1f643a39ace.png)

**Comment by stdavis** [comment]
Looks great. @steveoh Can I get a review on https://github.com/agrc/warehouse/pull/134?

**Comment by stdavis** [comment]
FYI... https://github.com/agrc/warehouse/pull/134#issuecomment-1028272260

**Comment by gregbunce** [comment]
steve and i are scheduled to meet with udot tomorrow morning to clarify the different datasets.

**Comment by gregbunce** [comment]
Update: let's hang tight for a little while longer. We are talking to udot about publishing their service with a more user-friendly name. This renamed service would be hidden in their org and only available to us to consume via open data.

**Comment by gregbunce** [comment]
update: udot republished the service under a new, more friendly name `Utah UDOT Mile Reference Posts`.  we are working on the details as to how they can share it with us, but keep it hidden in their public sites.

**Comment by gregbunce** [comment]
this item is no longer blocked.  ugrc and udot were able to work out a solution in which ugrc created a new item in agol and pointed it to udot's feature service.  this allows us to name the item whatever we want, while the data is fully managed by udot.  the only caveat is the metadata.  in this workflow, udot's metadata does not carry over so we have to copy it over manually, this if fine in this case b/c udot looks to us to create the metadata.  

this is the new ugrc layer that points to the udot's data. 
https://opendata.gis.utah.gov/datasets/utah::utah-udot-mile-reference-posts/explore

i'll get the data page updated with this data.

**Comment by gregbunce** [comment]
@stdavis hold off on your warehouse pr.  we should talk before you proceed.  the main thing: we need to pull our version of udot's layer during the 'farm to agol' process.  i'll hit you up tomorrow.  just letting you know, hold off on that aspect.

**Comment by gregbunce** [comment]
here's a draft preview of the ugrc data page, as it would look after we implement and complete this issue.
https://deploy-preview-1977--gis-utah-gov.netlify.app/data/transportation/roads-system/#MilepostPoints

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 172

| check | status |
| - | :-: |
| @gregbunce has completed **4** out of **8** tasks | :no_entry: |
| @stdavis has completed **0** out of **2** tasks | :no_entry: |
| @steveoh has completed **0** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| @rkelson has completed **0** out of **1** tasks | :no_entry: |

**Comment by steveoh** [comment]
@gregbunce this issue says you added the data to internal and created a meta record in early February but there is no open sgid item in transportation. Do I need to debug and figure out why or is something else going on?

**Comment by gregbunce** [comment]
i'm not aware of anything else going on.  i wonder if i added the meta row incorrectly.  does that look correct to you?  
![image](https://user-images.githubusercontent.com/16906316/159366016-176b1482-4704-4507-91e1-0abbfd92da8a.png)

**Comment by steveoh** [comment]
Other than you are in arcmap, yes it looks right.

**Comment by gregbunce** [comment]
@stdavis how will know if the process to update this layer in Internal from the source (AGOL) is working?  Do we have to wait for an update at the source to see if it's working?  

(the TMI version behind my question)
typically, i wouldn't be concerned, but on this layer, i have my reservations.   the reason is - this was not a direct load into Internal from the source.  i had to download it from UDOT as a shapefile (that was the only option) and then manually rename the field names to match the original UDOT web service (removing the odd shapefile field naming conventions).  long story short, I'm hoping i did it correctly and that all the fields names in Internal match the field names in the web service.

**Comment by stdavis** [comment]
It processed successfully in forklift yesterday:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1326248/159512531-fbcc8fed-a732-49fc-afb6-a7ea2610d012.png">

The best test is to wait for a change and make sure that it makes it through to internal and open data.

**Comment by gregbunce** [comment]
great, thanks.  i'll reach out to udot to see when a change might be coming, but it might be a while.  from my understanding, this layer has very few updates.  

thanks for the info.

**Comment by steveoh** [comment]
@gregbunce cloudb has been trying to import unsuccessfully since the 17th. I'll look into why that is. I'm guessing it's because you don't have the geometry type in the meta table...

**Comment by gregbunce** [comment]
thanks for the info.  yeah, that's an issue on my end.  i'll re-import the layer and get if fixed.  thanks!

**Comment by stdavis** [comment]
Looks like the forklift data in hashing was messed up. Not sure how. I deleted it and will let it run again tonight.

**Comment by gregbunce** [comment]
i have a feeling it's b/c the field names don't match up perfectly.  i probably mistyped a few of them.  I'm reaching to udot now to see if i can get a fdgb of this layer so i can reload it into Internal.  I tried to load the feature service into Internal but it errors out.  it's not supported..

**Comment by gregbunce** [comment]
i was able to get a fresh copy of this layer from udot in fgdb format.  i replaced the old (shapefile-derived) feature class with this new feature class.  fingers crossed.  i think this will solve our issues.

**Comment by gregbunce** [comment]
@stdavis it looks like the update process wiped out the fields again (the geometry seems fine). it should have about 21 fields, but it only has the required two. should i re-load a fresh copy of the data into Intneral?

![image](https://user-images.githubusercontent.com/16906316/159727535-76bde235-0924-4f2b-90ef-edd2664dc077.png)

**Comment by stdavis** [comment]
@gregbunce I believe that I have the data fixed in internal. It seems to be an issue with the older version of Pro on the forklift machine. I tested it on the new forklift machine in GCP and it worked fine. It also worked fine on my dev machine. 

@steveoh and I thought that this would be a good excuse to migrate to the new GCP forklift machine. Its first run will be tonight. 🤞

**Comment by gregbunce** [comment]
Thanks, Scott. I'll hang tight and check it tomorrow.

**Comment by gregbunce** [comment]
@stdavis your magic worked! aka: the fields are back in the Internal db.  everything looks good.  thanks for your persistence on this.

**Comment by steveoh** [comment]
the cloudb service is still having issues that i'm looking into

**Comment by gregbunce** [comment]
sneaky, hidden carriage returns in the meta table.  thanks for catching that steve.  that one is on me.

**Comment by agrc-conductor** [comment]
## conductor results for tasks - 172

| check | status |
| - | :-: |
| @gregbunce has completed **6** out of **9** tasks | :no_entry: |
| @stdavis has completed **1** out of **2** tasks | :no_entry: |
| @steveoh has completed **2** out of **4** tasks | :no_entry: |
| @jacobdadams has completed **0** out of **1** tasks | :no_entry: |
| rkelson has completed **1** out of **1** tasks | :+1: |

**Comment by gregbunce** [comment]
i think we're ready to close this issue out.  @steveoh and @jacobdadams it looks like you have the final checkboxes in the Automation validation section.  
the last one to check the boxes, feel free to close it out!  thanks!

**Comment by jacobdadams** [comment]
I've verified auditor 👍

**Comment by steveoh** [comment]
open sgid and the sgid index looks good. what's up with the red slash for arcgis online?

**Comment by steveoh** [comment]
I think this is good. welcome to the sgid.
